// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/guoapeng/props (interfaces: AppConfigProperties)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAppConfigProperties is a mock of AppConfigProperties interface.
type MockAppConfigProperties struct {
	ctrl     *gomock.Controller
	recorder *MockAppConfigPropertiesMockRecorder
}

// MockAppConfigPropertiesMockRecorder is the mock recorder for MockAppConfigProperties.
type MockAppConfigPropertiesMockRecorder struct {
	mock *MockAppConfigProperties
}

// NewMockAppConfigProperties creates a new mock instance.
func NewMockAppConfigProperties(ctrl *gomock.Controller) *MockAppConfigProperties {
	mock := &MockAppConfigProperties{ctrl: ctrl}
	mock.recorder = &MockAppConfigPropertiesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppConfigProperties) EXPECT() *MockAppConfigPropertiesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAppConfigProperties) Get(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockAppConfigPropertiesMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAppConfigProperties)(nil).Get), arg0)
}
