// Code generated by mockery v2.25.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppConfigProperties is an autogenerated mock type for the AppConfigProperties type
type AppConfigProperties struct {
	mock.Mock
}

type AppConfigProperties_Expecter struct {
	mock *mock.Mock
}

func (_m *AppConfigProperties) EXPECT() *AppConfigProperties_Expecter {
	return &AppConfigProperties_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *AppConfigProperties) Get(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AppConfigProperties_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AppConfigProperties_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *AppConfigProperties_Expecter) Get(key interface{}) *AppConfigProperties_Get_Call {
	return &AppConfigProperties_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *AppConfigProperties_Get_Call) Run(run func(key string)) *AppConfigProperties_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AppConfigProperties_Get_Call) Return(_a0 string) *AppConfigProperties_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppConfigProperties_Get_Call) RunAndReturn(run func(string) string) *AppConfigProperties_Get_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAppConfigProperties interface {
	mock.TestingT
	Cleanup(func())
}

// NewAppConfigProperties creates a new instance of AppConfigProperties. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppConfigProperties(t mockConstructorTestingTNewAppConfigProperties) *AppConfigProperties {
	mock := &AppConfigProperties{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
