// Code generated by mockery v2.25.0. DO NOT EDIT.

package mocks

import (
	mapper "github.com/guoapeng/gdbcTemplate/mapper"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	transaction "github.com/guoapeng/gdbcTemplate/transaction"
)

// GdbcTemplate is an autogenerated mock type for the GdbcTemplate type
type GdbcTemplate struct {
	mock.Mock
}

type GdbcTemplate_Expecter struct {
	mock *mock.Mock
}

func (_m *GdbcTemplate) EXPECT() *GdbcTemplate_Expecter {
	return &GdbcTemplate_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields:
func (_m *GdbcTemplate) BeginTx() (transaction.Transaction, error) {
	ret := _m.Called()

	var r0 transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func() (transaction.Transaction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() transaction.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GdbcTemplate_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type GdbcTemplate_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
func (_e *GdbcTemplate_Expecter) BeginTx() *GdbcTemplate_BeginTx_Call {
	return &GdbcTemplate_BeginTx_Call{Call: _e.mock.On("BeginTx")}
}

func (_c *GdbcTemplate_BeginTx_Call) Run(run func()) *GdbcTemplate_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GdbcTemplate_BeginTx_Call) Return(_a0 transaction.Transaction, _a1 error) *GdbcTemplate_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GdbcTemplate_BeginTx_Call) RunAndReturn(run func() (transaction.Transaction, error)) *GdbcTemplate_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CloseDB provides a mock function with given fields:
func (_m *GdbcTemplate) CloseDB() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GdbcTemplate_CloseDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseDB'
type GdbcTemplate_CloseDB_Call struct {
	*mock.Call
}

// CloseDB is a helper method to define mock.On call
func (_e *GdbcTemplate_Expecter) CloseDB() *GdbcTemplate_CloseDB_Call {
	return &GdbcTemplate_CloseDB_Call{Call: _e.mock.On("CloseDB")}
}

func (_c *GdbcTemplate_CloseDB_Call) Run(run func()) *GdbcTemplate_CloseDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GdbcTemplate_CloseDB_Call) Return(_a0 error) *GdbcTemplate_CloseDB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GdbcTemplate_CloseDB_Call) RunAndReturn(run func() error) *GdbcTemplate_CloseDB_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: sqlstr, args
func (_m *GdbcTemplate) Execute(sqlstr string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, sqlstr)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (sql.Result, error)); ok {
		return rf(sqlstr, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) sql.Result); ok {
		r0 = rf(sqlstr, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(sqlstr, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GdbcTemplate_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GdbcTemplate_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - sqlstr string
//   - args ...interface{}
func (_e *GdbcTemplate_Expecter) Execute(sqlstr interface{}, args ...interface{}) *GdbcTemplate_Execute_Call {
	return &GdbcTemplate_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{sqlstr}, args...)...)}
}

func (_c *GdbcTemplate_Execute_Call) Run(run func(sqlstr string, args ...interface{})) *GdbcTemplate_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *GdbcTemplate_Execute_Call) Return(_a0 sql.Result, _a1 error) *GdbcTemplate_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GdbcTemplate_Execute_Call) RunAndReturn(run func(string, ...interface{}) (sql.Result, error)) *GdbcTemplate_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: sqlstr, args
func (_m *GdbcTemplate) Insert(sqlstr string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, sqlstr)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (sql.Result, error)); ok {
		return rf(sqlstr, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) sql.Result); ok {
		r0 = rf(sqlstr, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(sqlstr, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GdbcTemplate_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type GdbcTemplate_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - sqlstr string
//   - args ...interface{}
func (_e *GdbcTemplate_Expecter) Insert(sqlstr interface{}, args ...interface{}) *GdbcTemplate_Insert_Call {
	return &GdbcTemplate_Insert_Call{Call: _e.mock.On("Insert",
		append([]interface{}{sqlstr}, args...)...)}
}

func (_c *GdbcTemplate_Insert_Call) Run(run func(sqlstr string, args ...interface{})) *GdbcTemplate_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *GdbcTemplate_Insert_Call) Return(_a0 sql.Result, _a1 error) *GdbcTemplate_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GdbcTemplate_Insert_Call) RunAndReturn(run func(string, ...interface{}) (sql.Result, error)) *GdbcTemplate_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// QueryForArray provides a mock function with given fields: sqlstr, args
func (_m *GdbcTemplate) QueryForArray(sqlstr string, args ...interface{}) mapper.RowsConvertor {
	var _ca []interface{}
	_ca = append(_ca, sqlstr)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 mapper.RowsConvertor
	if rf, ok := ret.Get(0).(func(string, ...interface{}) mapper.RowsConvertor); ok {
		r0 = rf(sqlstr, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mapper.RowsConvertor)
		}
	}

	return r0
}

// GdbcTemplate_QueryForArray_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryForArray'
type GdbcTemplate_QueryForArray_Call struct {
	*mock.Call
}

// QueryForArray is a helper method to define mock.On call
//   - sqlstr string
//   - args ...interface{}
func (_e *GdbcTemplate_Expecter) QueryForArray(sqlstr interface{}, args ...interface{}) *GdbcTemplate_QueryForArray_Call {
	return &GdbcTemplate_QueryForArray_Call{Call: _e.mock.On("QueryForArray",
		append([]interface{}{sqlstr}, args...)...)}
}

func (_c *GdbcTemplate_QueryForArray_Call) Run(run func(sqlstr string, args ...interface{})) *GdbcTemplate_QueryForArray_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *GdbcTemplate_QueryForArray_Call) Return(_a0 mapper.RowsConvertor) *GdbcTemplate_QueryForArray_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GdbcTemplate_QueryForArray_Call) RunAndReturn(run func(string, ...interface{}) mapper.RowsConvertor) *GdbcTemplate_QueryForArray_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: sqlstr, args
func (_m *GdbcTemplate) QueryRow(sqlstr string, args ...interface{}) mapper.RowConvertor {
	var _ca []interface{}
	_ca = append(_ca, sqlstr)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 mapper.RowConvertor
	if rf, ok := ret.Get(0).(func(string, ...interface{}) mapper.RowConvertor); ok {
		r0 = rf(sqlstr, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mapper.RowConvertor)
		}
	}

	return r0
}

// GdbcTemplate_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type GdbcTemplate_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - sqlstr string
//   - args ...interface{}
func (_e *GdbcTemplate_Expecter) QueryRow(sqlstr interface{}, args ...interface{}) *GdbcTemplate_QueryRow_Call {
	return &GdbcTemplate_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{sqlstr}, args...)...)}
}

func (_c *GdbcTemplate_QueryRow_Call) Run(run func(sqlstr string, args ...interface{})) *GdbcTemplate_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *GdbcTemplate_QueryRow_Call) Return(_a0 mapper.RowConvertor) *GdbcTemplate_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GdbcTemplate_QueryRow_Call) RunAndReturn(run func(string, ...interface{}) mapper.RowConvertor) *GdbcTemplate_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: sqlstr, args
func (_m *GdbcTemplate) Update(sqlstr string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, sqlstr)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (sql.Result, error)); ok {
		return rf(sqlstr, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) sql.Result); ok {
		r0 = rf(sqlstr, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(sqlstr, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GdbcTemplate_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GdbcTemplate_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - sqlstr string
//   - args ...interface{}
func (_e *GdbcTemplate_Expecter) Update(sqlstr interface{}, args ...interface{}) *GdbcTemplate_Update_Call {
	return &GdbcTemplate_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{sqlstr}, args...)...)}
}

func (_c *GdbcTemplate_Update_Call) Run(run func(sqlstr string, args ...interface{})) *GdbcTemplate_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *GdbcTemplate_Update_Call) Return(_a0 sql.Result, _a1 error) *GdbcTemplate_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GdbcTemplate_Update_Call) RunAndReturn(run func(string, ...interface{}) (sql.Result, error)) *GdbcTemplate_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewGdbcTemplate interface {
	mock.TestingT
	Cleanup(func())
}

// NewGdbcTemplate creates a new instance of GdbcTemplate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGdbcTemplate(t mockConstructorTestingTNewGdbcTemplate) *GdbcTemplate {
	mock := &GdbcTemplate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
